apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: micrometer-account-service-monitor
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: account-service-micrometer
  endpoints:
    - port: http
    - path: /q/metrics
